/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    application
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val javaFXModules = listOf(
    "base",
    "controls",
    "fxml",
    "swing",
    "media",
    "graphics"
)
val supportedPlatforms = listOf("linux", "mac", "win") // All required for OOP

dependencies {

    implementation("com.microsoft.sqlserver:mssql-jdbc:12.7.0.jre11-preview")

    // Use JavaFX
    val javaFxVersion = 21
    for (platform in supportedPlatforms) {
        for (module in javaFXModules) {
            implementation("org.openjfx:javafx-$module:$javaFxVersion:$platform")
        }
    }
}

application {
    // Define the main class for the application.
    mainClass.set("aziendaviaggi.App")
}
