/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aziendaviaggi;

import javafx.application.Application;

public class App {

    public static void main(String[] args) throws Exception {
        Application.launch(GUI.class, args);
    }
}
