/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aziendaviaggi;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;

public class App extends Application {
    
    @Override
    public void start(Stage primaryStage) throws Exception {
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/login.fxml"));
        Parent root = loader.load();
        Image icon = new Image("/logo.png");
        new SQLDatabaseConnection().connect();

        primaryStage.getIcons().add(icon);
        primaryStage.setTitle("Azienda Viaggi");
        primaryStage.setScene(new Scene(root));
        primaryStage.show();
    }

    public static void main(String[] args) throws Exception {
        launch(args);
    }
}
